# Project Metadata
sonar.projectKey=cryptovault-frontend
sonar.projectName=CryptoVault Frontend
sonar.projectVersion=1.0.0

# Paths to sources and tests
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.ts,src/**/*.spec.tsx

# Language and exclusions
sonar.language=ts
sonar.typescript.tsconfigPath=tsconfig.app.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,dist/**,src/assets/**,vite.config.ts,tailwind.config.js,postcss.config.js,eslint.config.js
